rm */*/*/wps-office2019-etmain.png
rm */*/*/wps-office-wppmain.png
rm */*/*/wps-office-wpsmain.png
rm */*/*/wps-office2019-etmain.png
rm */*/*/wps-office2019-pdfmain.png
rm */*/*/wps-office2019-wppmain.png
rm */*/*/wps-office2019-wpsmain.png
rm */*/*/wps-office-etmain.png
rm */*/*/wps-word-old.png
rm */*/*/wps-office2019-wppmain.png
rm */*/*/wps-office-pdfmain.png
rm */*/*/wps-office-kingsoft.png
rm */*/*/wps-office-uninstall.png
rm */*/*/wps-powerpoint-old.png
rm */*/*/wps-office2019-pdfmian.png
rm */*/*/adobe-flashplayer.png
rm */*/*/adobe-reader.png
rm */*/*/AdobeAIR.png
rm */*/*/AdobeReader.png
rm */*/*/AdobeReader10.png
rm */*/*/AdobeReader11.png
rm */*/*/AdobeReader12.png
rm */*/*/AdobeReader8.png
rm */*/*/AdobeReader9.png
rm */*/*/adobe-air.png
rm */*/*/adobeflashplugin.png
rm */*/*/fcitx-sogoupinyin.png
rm */*/*/sogoupinyin.png
rm */*/*/deepin.com.wechat.png
rm */*/*/foxitreader.png
rm */*/*/google-chrome-beta.png
rm */*/*/google-chrome-old.png
rm */*/*/google-chrome-stable.png
rm */*/*/google-chrome-unstable.png
rm */*/*/google-chrome.png
rm */*/*/google-music-manager.png
rm */*/*/google-musicmanager.png
rm */*/*/google-webdesigner.png
rm */*/*/opera-beta.png
rm */*/*/opera-browser.png
rm */*/*/opera-developer.png
rm */*/*/opera.png
rm */*/*/firefox-3.0.png
rm */*/*/firefox-3.5.png
rm */*/*/firefox-4.0.png
rm */*/*/firefox-aurora.png
rm */*/*/firefox-default.png
rm */*/*/firefox-developer-icon.png
rm */*/*/firefox-gtk3.png
rm */*/*/firefox-icon.png
rm */*/*/firefox-nightly-icon.png
rm */*/*/firefox-nightly.png
rm */*/*/firefox-original.png
rm */*/*/firefox-trunk.png
rm */*/*/firefox.png
rm */*/*/firefox3.png
rm */*/*/kylin-boxmanage.png
rm */*/*/kylin-ipmsg.png
rm */*/*/kylin-ksc-defender.png
rm */*/*/kylin-scanner.png
rm */*/*/kingsoft-writer.png
rm */*/*/kingsoft-spreadsheets.png
rm */*/*/kingsoft-presentation.png
rm */*/*/air.png
rm */*/*/application-mspowerpoint.png
rm */*/*/application-msexcel.png
rm */*/*/application-msword.png
rm */*/*/application-vnd.ms-excel.png
rm */*/*/application-vnd.ms-powerpoint.png
rm */*/*/application-vnd.ms-word.png
rm */*/*/application-vnd.openxmlformats-officedocument.presentationml.presentation.png
rm */*/*/application-vnd.openxmlformats-officedocument.presentationml.slideshow.png
rm */*/*/application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.png
rm */*/*/application-vnd.openxmlformats-officedocument.wordprocessingml.document.png
rm */*/*/application-wps-office.doc.png
rm */*/*/application-wps-office.dps.png
rm */*/*/application-wps-office.et.png
rm */*/*/application-wps-office.ppt.png
rm */*/*/application-wps-office.pptx.png
rm */*/*/application-wps-office.wps.png
rm */*/*/application-wps-office.wpss.png
rm */*/*/application-wps-office.xls.png
rm */*/*/application-wps-office.xlsx.png
rm */*/*/application-x-doc.png
rm */*/*/gnome-mime-application-wps-office.doc.png
rm */*/*/gnome-mime-application-wps-office.dps.png
rm */*/*/gnome-mime-application-wps-office.et.png
rm */*/*/gnome-mime-application-wps-office.ppt.png
rm */*/*/gnome-mime-application-wps-office.pptx.png
rm */*/*/gnome-mime-application-wps-office.wps.png
rm */*/*/gnome-mime-application-wps-office.wpss.png
rm */*/*/gnome-mime-application-wps-office.xls.png
rm */*/*/gnome-mime-application-wps-office.xlsx.png
rm */*/*/wps-office-doc.png
rm */*/*/wps-office-dot.png
rm */*/*/wps-office-dps.png
rm */*/*/wps-office-dpt.png
rm */*/*/wps-office-et.png
rm */*/*/wps-office-ett.png
rm */*/*/wps-office-pot.png
rm */*/*/wps-office-ppt.png
rm */*/*/wps-office-wps.png
rm */*/*/wps-office-xls.png
rm */*/*/wps-office-xlt.png

